version: '3.8'

services:
  web:
    build: 
      context: ./services/web
      # args:
      #   - IMAGE_NAME=""
      #   - IMAGE_TITLE=""
      #   - IMAGE_DESCRIPTION=""
      #   - IMAGE_VERSION
      #   - IMAGE_AUTHORS
      #   - IMAGE_VENDOR
      #   - IMAGE_CREATED
      #   - IMAGE_LICENSES
      #   - IMAGE_URL
      #   - IMAGE_DOCUMENTATION
      #   - IMAGE_SOURCE
      #   - IMAGE_REVISION
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --worker-class=gevent --log-level debug project.wsgi
    # command: tail -f /dev/null
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on: 
      - db

  db:
    image: mariadb
    command: --secure-file-priv=""
    ports:
      - 3307:3307
    environment:
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT:-3307}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-0000}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-db_dev}
      - MYSQL_USER=${MYSQL_USER:-dbmanager}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-0000}
    # volumes:
    #   - mysql:/var/lib/mysql
    #   - mysql_config:/etc/mysql
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE  https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log


# volumes:
#     mysql:
#     mysql_config:
